import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import client from '../api/client';
import MermaidRenderer from '../components/MermaidRenderer';

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// PNG export (FR-E2) draws the already-sanitized SVG onto a canvas at 2x
// for a crisper export, then reads it back out as a PNG blob. No server
// round-trip — the SVG mermaid.render() already produced is sufficient.
function downloadPng(svgString, filename) {
  const url = URL.createObjectURL(new Blob([svgString], { type: 'image/svg+xml' }));
  const img = new Image();
  img.onload = () => {
    const scale = 2;
    const canvas = document.createElement('canvas');
    canvas.width = img.width * scale;
    canvas.height = img.height * scale;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.scale(scale, scale);
    ctx.drawImage(img, 0, 0);
    canvas.toBlob((blob) => {
      downloadBlob(blob, filename);
      URL.revokeObjectURL(url);
    }, 'image/png');
  };
  img.src = url;
}

export default function DiagramDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [diagram, setDiagram] = useState(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  const [title, setTitle] = useState('');
  const [syntax, setSyntax] = useState('');
  const [liveSvg, setLiveSvg] = useState('');
  const [dirty, setDirty] = useState(false);

  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    client
      .get(`/api/diagrams/${id}`)
      .then((res) => {
        setDiagram(res.data);
        setTitle(res.data.title);
        setSyntax(res.data.mermaidSyntax);
      })
      .catch((err) => {
        if (err.status === 404) setNotFound(true);
        else setError(err.message);
      })
      .finally(() => setLoading(false));
  }, [id]);

  const handleSave = async () => {
    setError(null);
    setSaving(true);
    try {
      const res = await client.patch(`/api/diagrams/${id}`, { title, mermaidSyntax: syntax });
      setDiagram(res.data);
      setDirty(false);
    } catch (err) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!window.confirm('Delete this diagram? This cannot be undone.')) return;
    try {
      await client.delete(`/api/diagrams/${id}`);
      navigate('/diagrams');
    } catch (err) {
      setError(err.message);
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(syntax);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  if (loading) return <p className="p-8 text-sm text-slate-500">Loading…</p>;
  if (notFound) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-8">
        <p className="text-sm text-slate-600">
          This diagram doesn't exist, or isn't yours to see. If you followed a link, double-check it's correct.
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-5xl px-4 py-8">
      <input
        value={title}
        maxLength={120}
        onChange={(e) => {
          setTitle(e.target.value);
          setDirty(true);
        }}
        className="w-full border-none text-2xl font-semibold text-slate-900 focus:outline-none"
      />
      <p className="text-xs text-slate-400">
        {diagram.diagramType} · generated by {diagram.providerUsed || 'unknown'}
      </p>

      <div className="mt-6 grid gap-6 md:grid-cols-2">
        <div>
          <label className="block text-sm font-medium text-slate-700">Mermaid syntax</label>
          <textarea
            rows={16}
            value={syntax}
            onChange={(e) => {
              setSyntax(e.target.value);
              setDirty(true);
            }}
            className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 font-mono text-xs focus:border-slate-500 focus:outline-none"
          />
          <div className="mt-3 flex flex-wrap gap-2">
            <button
              onClick={handleSave}
              disabled={!dirty || saving}
              className="rounded-md bg-slate-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-slate-700 disabled:opacity-40"
            >
              {saving ? 'Saving…' : 'Save changes'}
            </button>
            <button
              onClick={handleCopy}
              className="rounded-md border border-slate-300 px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50"
            >
              {copied ? 'Copied!' : 'Copy source'}
            </button>
            <button
              onClick={() => downloadBlob(new Blob([liveSvg], { type: 'image/svg+xml' }), `${title || 'diagram'}.svg`)}
              disabled={!liveSvg}
              className="rounded-md border border-slate-300 px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50 disabled:opacity-40"
            >
              Download SVG
            </button>
            <button
              onClick={() => downloadPng(liveSvg, `${title || 'diagram'}.png`)}
              disabled={!liveSvg}
              className="rounded-md border border-slate-300 px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50 disabled:opacity-40"
            >
              Download PNG
            </button>
            <button
              onClick={handleDelete}
              className="ml-auto rounded-md border border-red-200 px-3 py-1.5 text-sm text-red-600 hover:bg-red-50"
            >
              Delete
            </button>
          </div>
          {error && <p className="mt-2 text-sm text-red-600">{error}</p>}
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700">Preview</label>
          <div className="mt-1">
            <MermaidRenderer syntax={syntax} onRendered={setLiveSvg} />
          </div>
        </div>
      </div>
    </div>
  );
}
