import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import client from '../api/client';
import MermaidRenderer from '../components/MermaidRenderer';

const DIAGRAM_TYPES = ['flowchart', 'sequence', 'class', 'er', 'state', 'gantt', 'mindmap'];

export default function GeneratePage() {
  const navigate = useNavigate();
  const [text, setText] = useState('');
  const [diagramType, setDiagramType] = useState('');
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const [title, setTitle] = useState('');
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState(null);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setError(null);
    setResult(null);
    setGenerating(true);
    try {
      const res = await client.post('/api/diagrams/generate', {
        text: text.trim(),
        ...(diagramType ? { diagramType } : {}),
      });
      setResult(res.data);
      setTitle(res.data.title);
    } catch (err) {
      // 429 DAILY_CAP_EXCEEDED, 429 RATE_LIMITED, 502 LLM_INVALID_OUTPUT,
      // and 503 LLM_UNAVAILABLE (docs/functional-spec.md §8) all land here
      // with a message already written for a human to read directly.
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  };

  // Generation (FR-G7) and saving are deliberately separate requests —
  // nothing is persisted until this fires. See docs/adr/0005.
  const handleSave = async () => {
    if (!result) return;
    setSaveError(null);
    setSaving(true);
    try {
      const res = await client.post('/api/diagrams', {
        title,
        sourceText: text.trim(),
        diagramType: result.diagramType,
        mermaidSyntax: result.mermaidSyntax,
        providerUsed: result.providerUsed,
        generationMs: result.generationMs,
      });
      navigate(`/diagrams/${res.data._id}`);
    } catch (err) {
      setSaveError(err.message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="mx-auto max-w-5xl px-4 py-8">
      <h1 className="text-2xl font-semibold text-slate-900">Generate a diagram</h1>
      <p className="mt-1 text-sm text-slate-500">
        Describe a process, system, or data model in plain English.
      </p>

      <form onSubmit={handleGenerate} className="mt-6 grid gap-6 md:grid-cols-2">
        <div className="space-y-4">
          <div>
            <textarea
              required
              maxLength={2000}
              rows={8}
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="e.g. user submits an order, we check stock, if available charge the card and ship, otherwise refund"
              className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm focus:border-slate-500 focus:outline-none"
            />
            <p className="mt-1 text-right text-xs text-slate-400">{text.length}/2000</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700">Diagram type</label>
            <select
              value={diagramType}
              onChange={(e) => setDiagramType(e.target.value)}
              className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm focus:border-slate-500 focus:outline-none"
            >
              <option value="">Let the AI decide</option>
              {DIAGRAM_TYPES.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </div>

          <button
            type="submit"
            disabled={generating || text.trim().length === 0}
            className="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 disabled:opacity-50"
          >
            {generating ? 'Generating…' : 'Generate'}
          </button>

          {error && (
            <div className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>
          )}
        </div>

        <div className="space-y-4">
          {result ? (
            <>
              <MermaidRenderer syntax={result.mermaidSyntax} />
              <p className="text-xs text-slate-400">
                Generated by <span className="font-medium">{result.providerUsed}</span> in{' '}
                {result.generationMs}ms
              </p>

              <div>
                <label className="block text-sm font-medium text-slate-700">Title</label>
                <input
                  type="text"
                  maxLength={120}
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm focus:border-slate-500 focus:outline-none"
                />
              </div>

              <button
                onClick={handleSave}
                disabled={saving}
                className="rounded-md border border-slate-300 px-4 py-2 text-sm font-medium text-slate-900 hover:bg-slate-50 disabled:opacity-50"
              >
                {saving ? 'Saving…' : 'Save diagram'}
              </button>

              {saveError && <p className="text-sm text-red-600">{saveError}</p>}
            </>
          ) : (
            <div className="flex h-full min-h-48 items-center justify-center rounded-md border border-dashed border-slate-300 text-sm text-slate-400">
              Your diagram will appear here
            </div>
          )}
        </div>
      </form>
    </div>
  );
}
